### ISSUE TITLE
[BUG] Issues when installing profile

### ISSUE THREAD

**Issue by ATXLtheAxolotl** [FrederoxDev/Amethyst-Launcher#1] opened 2024-02-02 21:43 UTC
Version: `2.1.0-pre-release`
Profile: `1.20.51.1`
Type: `Vanilla`

When you start the launcher without a a mods folder in Amethyst the launcher throws an error, leaving the screen white.
```
Uncaught Error: ENOENT: no such file or directory, scandir 'C:\Users\USER\AppData\Local\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\AC\Amethyst\mods'
    at Object.readdirSync (node:fs:1527:3)
    at t.readdirSync (node:electron/js2c/asar_bundle:2:11295)
    at Modlist.ts:23:28
    at AppState.tsx:61:25
    at as (react-dom.production.min.js:244:332)
    at xu (react-dom.production.min.js:286:111)
    at react-dom.production.min.js:282:391
    at k (scheduler.production.min.js:13:203)
    at Immediate.R (scheduler.production.min.js:14:128)
    at process.processImmediate (node:internal/timers:476:21) 
```

When the launcher is registering the downloaded game it asks me to use the Microsoft store to find something to open the Minecraft url.
![image](https://github.com/FrederoxDev/Amethyst-Launcher/assets/49346095/9d77bc31-c4d6-48f7-862a-454c8520a935)

**Comment by FrederoxDev** [comment] 2024-02-02 22:20
Does the open in Microsoft store issue persist or is it just a one time issue when you install the version for the first time?

Also for now just manually make the mod folder, will fix in the next update 👍

**Comment by ATXLtheAxolotl** [comment] 2024-02-02 22:26
The Microsoft store prompt is a reoccurring issue that I have.

**Comment by FrederoxDev** [comment] 2024-02-02 22:28
Could you try deleting the downloaded version of 1.20.51.1? It will be installed in amethysts folder in app data. Simply just delete the .appx file and the folder in the versions folder.

Then try launching again

**Comment by ATXLtheAxolotl** [comment] 2024-02-02 22:34
I seem to still have the issue after deleting the version.

**Comment by FrederoxDev** [comment] 2024-02-02 22:36
Just to double check it went through all the steps of downloading and unzipping the version?

Maybe it's failing to register the version.. every time you press launch does it try to register again?

If so try running it in admin

**Comment by FrederoxDev** [comment] 2024-02-02 22:37
If it doesn't work with admin try pressing CTRL + SHIFT + I and go to console, see if there is anything logged there

**Comment by ATXLtheAxolotl** [comment] 2024-02-02 22:42
The launcher showed the zip state but I didn’t check the console nor try it in administrator. Once I get back from dinner, I will have to reinstall the game through another launcher first since Amethyst-Launcher requires the mods folder on launch. I’m suspecting its an admin issue but it could be the zip

**Comment by ATXLtheAxolotl** [comment] 2024-02-03 03:27
The issue persists when ran in admin. The zip output had no issues and no errors were printed to console.

**Comment by ATXLtheAxolotl** [comment] 2024-02-03 03:30
I'm going to try and log the powershell registration command and see if it has any issues.

**Comment by ATXLtheAxolotl** [comment] 2024-02-03 04:00
Well I fixed it but I can't remember what I changed, give me a minute to make a PR. my brain is too tired

**Comment by ATXLtheAxolotl** [comment] 2024-02-03 04:17
Fixed it somewhat I just now get this strange prompt:
![image](https://github.com/FrederoxDev/Amethyst-Launcher/assets/49346095/04857cad-5eaa-42f9-85a5-9e900709c12f)

**Comment by ATXLtheAxolotl** [comment] 2024-02-03 04:21
Strangely enough the game seems to self-terminate when it has a launcher_config.json I'm guessing the proxy doesn't like the vanilla runtime

**Comment by ATXLtheAxolotl** [comment] 2024-02-03 04:32
Resolved by #2

**Comment by FrederoxDev** [comment] 2024-02-04 12:15
> Strangely enough the game seems to self-terminate when it has a launcher_config.json I'm guessing the proxy doesn't like the vanilla runtime

Yeah the vanilla option hasn't been implemented yet xd, known issue.

Right now the runtime just instantly closes itself, which takes the game down with it.

**Comment by KerbinCenturion** [comment] 2024-04-11 20:37
I am having the same issue with the program asking me to use the Microsoft store to find something to open the Minecraft URL.
When I "register" the program in Amethyst it deletes the base Minecraft game and then the store popup gets displayed, I have tried a lot of things so far but no dice.

**Comment by ATXLtheAxolotl** [comment] 2024-04-11 20:39
Yeah it tends to do this when it fails to install the game; I’m thinking we should move back the data restore point if it fails at some point in the re-install game.

**Comment by FrederoxDev** [comment] 2024-04-11 20:41
Yeah, the issue is that we haven't really had a way to reproduce this issue. Could we get some information?:

- Have you ever used other version switchers? (Including the official minecraft one for Java, which includes a way to install bedrock)
- Does minecraft show up in the list of apps in "Add or remove programs" in windows settings?
- What version of the game did you try do install through Amethyst?

**Comment by FrederoxDev** [comment] 2024-04-11 20:44
P.s. all your games data should be in the `%appdata%/Amethyst/DataRestorePoint/` folder, it might be worth making a manual copy if you have stuff you care about in there

**Comment by Tallis-Larsen** [comment] 2024-04-14 19:57
1: I did use the minecraft launcher to switch between latest java release and 1.8 for combat purposes a while ago.
2. No. only the minecraft launcher and minecraft preview do
3. Latest release (1.20.73. i believe)

**Comment by FrederoxDev** [comment] 2024-04-14 22:18
Thanks, from some debugging we eventually figured out that:
 - we have an issue where downloading can occasionally freeze
 - there is an issue with registering the downloaded package
    - we found that it was possible to manually register the package through a powershell instance
    - developer mode had to be enabled through win settings

If we get another person having these issues:
 - we should first try getting them to enable developer mode and see if that was the issue with the registering. If not, get them to also run the command in powershell `Add-AppxPackage -Path "C:\Users\<USER NAME>\AppData\Roaming\Amethyst\versions\Minecraft-1.20.73.1\AppxManifest.xml" -Register` and see if that works.

**Comment by FrederoxDev** [comment] 2024-04-15 20:58
Should be automatically handled in launcher version 2.3.0, commit: 1b1add47341345d3710fc3607bed1fe24c7e3e63

**Closed as completed by FrederoxDev** 2024-04-15 20:58 UTC

**Comment by KerbinCenturion** [comment] 2024-04-16 20:57
> I am having the same issue with the program asking me to use the Microsoft store to find something to open the Minecraft URL. When I "register" the program in Amethyst it deletes the base Minecraft game and then the store popup gets displayed, I have tried a lot of things so far but no dice.

I fixed this by enabling developer setting in Windows, I had the same thing for days but this fixed it for me.

**Comment by FrederoxDev** [comment] 2024-04-16 20:59
Sweet, good to hear, the latest release of the launcher should fully handle this now, so hopefully no more new users will run into this.

**Comment by Xplodin** [comment] 2026-06-26 01:34
<img width="455" height="192" alt="Image" src="https://github.com/user-attachments/assets/eb4b6212-4ea2-457f-8550-3a193e3b6c46" />

I still get it

Had to enable dev settings in windows to fix

**Comment by Tallis-Larsen** [comment] 2026-06-26 02:24
Well now that everyone just got a notification on a two year old thread, let's throw a party! :P

**Comment by Xplodin** [comment] 2026-06-26 04:13
"oops" 
Figured it would be better to not duplicate a thread and instead keep it isolated

**Comment by Tallis-Larsen** [comment] 2026-06-26 05:18
Nah, idc (not like I even have a right to); AFAIC, it means you read the existing issues before posting. Freddy, on the other hand, will be PISSED. His dad is the CEO of Minecraft, so you can kiss your minecoins goodbye.
